wangeditor-team/wangEditor

dist/js/wangEditor.js

Issue #271 'Add upload request headers support'

---

test/angular/test-angular.html

初始化编辑器内容显示，ng-model双向绑定表单效果

---

docs/usage/03-config/09-focus.md
docs/usage/03-config/10-blur.md
package.json
src/js/editor/index.js

新增了focus事件和blur事件及文档
版本升级为3.0.12
因为我是windows环境 打包出来的缩进格式有差别 会导致打包出来的文件和原文件看起来有有很多的修改
所以我这次只修改了源代码并没有做打包构建

新增focus与blur事件

---

src/menus/code/create-panel-conf.ts

fix:修复highlight代码解析错误

---

docs/README.md
package.json
server/www.js

启动服务 输出 访问地址 和 一次性运行 dev & example

Feature server console url

---

examples/indent-conf.html
src/config/index.ts
src/config/menus.ts
src/menus/indent/decrease-indent-style.ts
src/menus/indent/increase-indent-style.ts
src/menus/indent/operate-element.ts

需求 https://github.com/wangeditor-team/wangEditor/issues/2324
添加了example

feat: 缩进功能支持config选项indentation，用来指定缩进量

---

docs/pub.md
src/text/paste/parse-html.ts

fix:某些情况下，无法成功粘贴

---

examples/form.html
examples/table.html
src/menus/code/create-panel-conf.ts
src/menus/img/create-panel-conf.ts
src/menus/link/create-panel-conf.ts
src/menus/table/create-panel-conf.ts
src/menus/video/create-panel-conf.ts
src/text/index.ts
src/utils/dom-core.ts

form 触发 submit bug && 外围 table 唤起 toolbar bug

Fix tonghan 2020 12 2

---

src/text/index.ts

设置focus为false，第一次点击编辑框，没有触发saveRange。

fix: 修复设置focus为false,无法正常粘贴的问题

---

src/editor/selection.ts
src/menus/head/index.ts

fix: 修复选中多行文本时无法设置head的问题

---

src/menus/font-color/index.ts

fix: 修复a标签设置颜色，按下回车后颜色值失效的问题

---

src/menus/table/create-panel-conf.ts
src/menus/table/create-table.ts
src/menus/todo/bind-event/index.ts
src/menus/todo/util.ts

todo 删除报错
表格验证列表标签到编辑器外了
表格验证行列参数为正整数

Fix tonghan 2021 1 20

---

src/menus/table/bind-event/index.ts
src/menus/table/bind-event/keyboard.ts
src/menus/todo/bind-event/index.ts

fix: 保证table后面始终有dom

---

cypress/integration/e2e/menus/hr.spec.ts
src/editor/selection.ts
src/menus/split-line/index.ts
src/utils/dom-core.ts

修复由于一些操作导致的控制台报 nodeName 未定义的错误

fix: 修复由于某些操作导致的控制台报undefined的错误

---

src/text/index.ts

*[issue 2872](https://github.com/wangeditor-team/wangEditor/issues/2872)*
*能够正常添加行、列，以及删除等操作*
*是*

fix: issue-2872

---

src/config/events.ts
src/config/index.ts
src/editor/init-fns/bind-event.ts

https://github.com/wangeditor-team/wangEditor/issues/2833

perf: 不传入config.onchange时，避免不必要的Text.html调用

---

cypress/integration/e2e/menus/emotion.spec.ts
src/config/lang.ts
src/config/menus.ts

fix: 增加默认表情

---

examples/upload-image.html
examples/upload-img-accept-empty.html
src/menus/img/upload-img.ts

修复editor.config.uploadImgAccept设置无效的bug。

fix: 修复上传图片格式的验证配置

---

examples/upload-image.html
src/menus/img/bind-event/paste-img.ts

fix: 修复v4版本中，复制图片-粘贴-走自定义上传逻辑。粘贴的内容中有File就执行上传的逻辑，没有就判断text/html。

fix: 复制图片-粘贴-走自定义上传逻辑

---

src/menus/code/bind-event/jump-code-block-down.ts

fix: 修复代码块作为最后一个元素时,用户无法输入的问题

---

examples/custom-tooltipshow.html
src/assets/style/menus.less
src/assets/style/text.less
src/config/index.ts
src/config/menus.ts
src/menus/index.ts

1. 新增菜单项tooltip上下标可自定义选择功能
2. 将text.less中关于菜单项tooltip的样式设置移至menu.less中

fix: 菜单tooltip上标下标自定义配置

---

src/text/index.ts

fix: 修复鼠标移出编辑区后获取选区异常

---

.github/workflows/release.yml
CHANGELOG.md
package.json

code  review完成后我需要把我们最新版本的一个tag转换成release才可以正常运行脚本

chore: 增加release自动发布的功能

---

.github/workflows/release.yml

chore: 修改release的token值

---

src/menus/code/create-panel-conf.ts

fix: 修复插入代码异常问题

---

examples/customMenu.html
src/menus/index.ts

fix: 修复排除自扩展菜单

---

LICENSE
README-en.md
README.md

修改了LICENSE时间为2020-2021
修改了中英文文档License为MIT

docs: 修改协议为MIT和版权时间

---

examples/index.html
src/editor/init-fns/init-dom.ts

fix: 修复placeholder中不能含有点(.)的问题

---

src/menus/lineHeight/index.ts

修复ie11下p重复插入导致内容被删除 及 多行在ie下未进行处理 #3238

fix: 修复ie11下 设置行高无效、多行无效和内容消失

---

src/menus/table/bind-event/event/operating-event.ts

fix: 设置/取消表头不删除第一行

---

src/text/index.ts

Fix delete one letter can delete before img

---

packages/core/src/text-area/event-handlers/composition.ts

Reverts wangeditor-team/wangEditor#4887

Revert "fix: 修复 compositionend 时错误修改dom的问题"

---

packages/core/src/menus/bar/HoverBar.ts
packages/core/src/menus/bar/Toolbar.ts

fix: mousedown事件添加passive的默认值

---

packages/basic-modules/__tests__/indent/menu/decrease-indent-menu.test.ts
packages/basic-modules/__tests__/indent/menu/increase-indent-menu.test.ts
packages/basic-modules/src/modules/indent/menu/IncreaseIndentMenu.ts

fix(indent menu): 修复了因为设置 fontSize 导致 text-indent 没法对齐的问题
