wangeditor-team/wangEditor

- test/angular/test-angular.html
原先的集成在contenteditable下的ngModel无法实现双向绑定的内容初始化
> 集成angularjs的编辑器初始化内容

- src/js/editor/index.js
- src/less/menus.less
修复 #1223 
输入法在输入状态时，并未输入完成，触发了`change`事件。
经测试原生`input`并无此现象，查询发现change事件触发应该在**IME（input method editor）的启动和关闭后触发**，对应的事件为`compositionstart`和`compositionend`
> 修复 在输入法输入未完成时触发change事件

- src/js/selection/index.js
当需要自定义插入的组件时，比如：
常常会需要将组件的容器的 `contenteditable` 设置为 `false`，以防用户改动组件内容，但如果鼠标点击该组件，选区将进入到该不可编辑的容器之中，此时会导致无法使用 `insertHTML` 命令插入新的内容。
> 修复点击编辑器内的不可编辑区域时丢失选区的Bug

- src/text/paste/parse-html.ts
*当一串文字中间有部分有加粗或者下划线，且左右两侧有空格时，复制该段文字，然后粘贴，中间的空格部分会被清空。官网可复现。*
*执行以上操作，粘贴的文字中间空格部分保留。*
*是*
> fix: 粘贴文字中间空格保留

- src/text/paste/parse-html.ts
*当一串文字中间有部分有加粗或者下划线，且左右两侧有空格时，复制该段文字，然后粘贴，中间的空格部分会被清空。官网可复现*。  
*执行以上操作，粘贴的文字中间空格部分保留。*     
*是*
> fix: 粘贴文字保留空格

- src/editor/init-fns/set-full-screen.ts
*当最后一行是文字，设置全屏出现滚动条时，最后一行文本不可见。*
*设置全屏时，最后一行文本在可视区域内可见。*
*是*
> fix: 最后一行文本看不见

- src/editor/index.ts
- src/editor/init-fns/bind-event.ts
- src/menus/menu-constructors/Tooltip.ts
- src/text/index.ts
- test/unit/menus/tooltip.test.ts
解决bug编辑器失去焦点和销毁tooltip不消失问题
bind-event.ts 去掉 if(editor.focus) 原因是有些地方用到了event.stopPropagation方法导致失去焦点事件无法触发
在失去焦点和销毁编辑器的时候调用editor.txt.eventHooks.toolbarClickEvents.forEach(fn => fn(event))钩子来移除tooltip
> fix: 失去焦点tooltip不消失

- src/editor/init-fns/init-dom.ts
解决该issue 
#2720
在text 与 bar 分离时, 追加子节点而不是修改用户传入的节点
> bar 与 text 分离的情况下, 追加子节点来生成编辑器dom

- src/lib/simplehtmlparser.js
解决parseAttributes正则匹配后参数少传了一位，导致parseAttribute中arguments[8]取到的值是undefined，最终标签属性设置错误问题。
*在复制一个带样式的内容到富文本框时样式丢失，调试发现是parseAttributes方法在正则匹配后处理参数时少传了一位，导致后面parseAttribute中arguments[8]取到的值是undefined
在关闭样式过滤功能后复制的带样式内容能够正确显示样式
拷贝一份样式或属性带有单引号的内容（例如从world中拷贝一个表格）到富文本中，样式和属性丢失。
*是
> fix:解决单引号属性parse后变undefined问题

- src/text/index.ts
*[#2903](https://github.com/wangeditor-team/wangEditor/issues/2903)*
*右键不会导致选区取消*
*是*
> fix: 修复右键取消选区bug

- src/assets/style/disable.less
- src/assets/style/text.less
设置编辑器分离后不显示内容的原因跟逻辑代码没有关系， 就是样式上的问题，
此外当编辑区域与菜单分离的时候， 编辑区域聚焦有问题 就给  .w-e-text-container 样式加了高度100%
> fix: 菜单分离后禁止编辑器内容不显示

- cypress/integration/e2e/txt/append.spec.ts
- src/editor/init-fns/init-dom.ts
- src/editor/init-fns/init-selection.ts
- src/editor/selection.ts
- src/menus/code/bind-event/jump-code-block-down.ts
- src/menus/code/create-panel-conf.ts
- src/menus/head/index.ts
- src/menus/quote/bind-event/index.ts
- src/menus/quote/index.ts
- src/menus/split-line/index.ts
- src/menus/table/bind-event/tooltip-event.ts
- src/menus/table/create-table.ts
- src/menus/todo/bind-event/index.ts
- src/menus/video/create-panel-conf.ts
- src/menus/video/upload-video.ts
- src/text/event-hooks/del-to-keep-p.ts
- src/text/event-hooks/enter-to-create-p.ts
- src/text/event-hooks/index.ts
- src/text/index.ts
- src/utils/const.ts
- test/unit/editor/history/decompile.test.ts
- test/unit/menus/redo.test.ts
- test/unit/menus/table/create-table.test.ts
- test/unit/menus/undo.test.ts
- test/unit/menus/video/upload-video.test.ts
- test/unit/text/del-to-keep-p.test.ts
- test/unit/text/enter-to-create-p.test.ts
- test/unit/text/index.test.ts
相关 issue #2673
编辑器主动生成的占位空标签 由 ```<p><br></p>``` 改成  ```<p data-we-empty-p><br></p>```
避免误删 用户自己输入的 空标签
> fix: 默认设置空行由<p><br></p>改成<p data-we-empty-p=""><br></p>

- src/text/index.ts
ie上，在编辑器范围内mousedown，然后在编辑器外mouseup，依然会触发编辑器的mouseup事件。
鼠标移到编辑器外部，触发了mouseleave，保存了选区（有选中内容）。然后松开鼠标，触发了编辑器mouseup（ie上才会），保存选区，走进了原来mouseup中的if，选区被改成没有选中内容。导致加粗、设置字体大小之类的失败
> fix: 在ie编辑器外部mouseup,选区保存错误

- cypress/integration/e2e/menus/align.spec.ts
- cypress/integration/e2e/menus/bg.spec.ts
- cypress/integration/e2e/menus/fontColor.spec.ts
- cypress/integration/e2e/menus/fontFamily.spec.ts
- cypress/integration/e2e/menus/fontSize.spec.ts
- cypress/integration/e2e/menus/indent.spec.ts
- cypress/integration/e2e/menus/lineHeight.spec.ts
- cypress/integration/e2e/menus/list.spec.ts
- src/menus/menu-constructors/DropList.ts
- src/menus/menu-constructors/DropListMenu.ts
- test/unit/menus/droplist-menu.test.ts
1. 将mouseenter事件引起droplist菜单显示改为click事件
2. 将jest与cypress模拟mouseenter事件同步为click事件
> fix: 将hover引起droplist菜单显示改为click

- examples/jq-create-dom.html
- src/editor/init-fns/init-dom.ts
- test/helpers/create-editor.ts
- test/unit/editor/create-editor.test.ts
菜单文本区域分离后，文本区域默认设置带标签的内容（只处理带标签的内容，纯文本不考虑），需要带入编辑器内
> fix: 修复textSelector中带标签的内容不能带入编辑器内

- examples/upload-video.html
- src/menus/video/bind-event/index.ts
- src/menus/video/bind-event/keyboard.ts
- src/menus/video/upload-video.ts
- test/unit/menus/video/upload-video.test.ts
chrome和firefox对 video标签 行为不一致， 所以针对firefox做特别处理， 使firefox在行为上尽量看起来和chrome表现一只
> fix: 兼容火狐浏览器video标签存在时光标无法输入问题

- examples/auto-focus.html
- src/editor/init-fns/bind-event.ts
解决当用户设置isFocus为false的情况下，编辑器初始化完成后点击其他元素依旧会触发blur事件的问题
> fix: 修复设置isFocus为false的情况下，初始化完成后依旧触发blur事件的问题

- src/menus/img/bind-event/paste-img.ts
- src/text/event-hooks/paste-text-html.ts
卡死原因是正则性能较差，修改正则即可。同时在粘贴过程中有另外的问题也会导致粘贴图片耗时较长，一并fix
> fix: 粘贴图片性能问题

- src/menus/table/bind-event/event/getNode.ts
- src/menus/table/bind-event/event/operating-event.ts
- src/menus/table/bind-event/tooltip-event.ts
- src/text/index.ts
解决了两个问题
1. 解决在 执行 ```editor.txt.append```, ```editor.txt.html``` 时意外清除已存在html空格 的问题
2. 解决了 编辑器中出现了带有空白换行符的table时, table的添加/删除 行列失败
(因为该issue 出现是之前为了修改另一个关于table issue出现, 所以修改后, 之前那个table 的issue
也需要再测试一下  https://github.com/wangeditor-team/wangEditor/issues/2872  )
> feat: 修复了append 时意外清除空格的问题

- src/text/index.ts
- test/unit/text/index.test.ts
修复鼠标选中文字之后，再选择文字中间位置插入图片导致选中文字消失的问题
这个问题不止是插入图片的时候会发生，选中之后再选择文字中间热任何位置去插入表情和图片都会造成，选中文字丢失的情况。
定位到的原因是因为第二次点击时的selection区域没有被获取到
> fix: 修复鼠标选中文字之后，再选择文字中间位置插入图片导致选中文字消失的问题

- examples/todo.html
- src/menus/todo/bind-event/index.ts
- src/menus/todo/todo.ts
出现bug原因是input默认没有style上的更新，dom中attribute没有变化，致使change没有监听到。
解决：在初始化时，给input绑定事件，以达到点击时attribute更新的效果，从而触发change。
> fix: 修复默认todo没有触发change的问题

- src/text/event-hooks/del-to-keep-p.ts
- src/text/index.ts
- test/unit/text/del-to-keep-p.test.ts
解决方法：
- 更改判断编辑器内容是否为空的条件
- 增加delete按键的监听
> fix: 修复全选删除文本无法删除干净的问题

- src/editor/disable/index.ts
- src/editor/index.ts
- src/editor/init-fns/scroll-to-head.ts
- test/unit/editor/disable.test.ts
由于使用状态和禁用状态下操作的是两个dom， 所以会导致scrollToHead功能失效。
发现现在编辑器并没有暴露出编辑器是否禁用状态，考虑到之后可能还会用到是否禁用这个状态， 所以在 editor/index.ts下增加isEnable属性来获取编辑器是否已被禁用, 并在执行{disable, enable} 方法中同步更新该状态
> fix: 修复禁用状态下scroll-to-head功能失效

- examples/index.html
- src/menus/menu-constructors/Panel.ts
* 设置默认offset，当偏移量过大，将菜单设置在toolbar icon下方
* 考虑左右边界位置
* 最终目的 - 修复panel菜单position位置的问题
> fix: 修复panel菜单position位置的问题

- .github/workflows/release.yml
- .github/workflows/test.yml
CI 任务：https://github.com/wangeditor-team/wangEditor/actions/runs/3353870191 报错，发现是因为第三方包升级代码增加了可选链语法导致的问题。
> fix(ci): 修复因 node 版本过低导致第三方包可选链语法不支持的问题
